version: '3'
services:

demo-server-instance-1:
  image: menglong567:demo-server-img
  volumes:
    - /disk-2/data/docker_instances_log_store/demo-server/cluster_instance_1:/logs
  depends_on:
    - eureka-server-instance-1
    - eureka-server-instance-2
    - config-server-instance-1
    - config-server-instance-2
  container_name: demo-server-instance-1
  #network_mode:
  networks:
    extnetwork:
      ipv4_address: 172.19.0.8
  ports:
    - 7777:7777
  environment:
    - SPRING_PROFILES_ACTIVE=cluster_instance_1
    - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://server1:8761/eureka/,http://server2:8762/eureka/
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root
    - SPRING_DATASOURCE_URL=jdbc:mysql://172.19.0.10:3306/demo_service_db
    - SPRING_DATASOURCE_TOMCAT_TEST-ON-BORROW=true
    - SPRING_DATASOURCE_TOMCAT_TEST-ON-CONNECT=true
    - SPRING_DATASOURCE_TOMCAT_MAX-ACTIVE=20
    - SPRING_DATASOURCE_TOMCAT_MAX-WAIT=10000
    - SERVER_PORT=7777
  external_links:
    - mysql
  extra_hosts:
    - "server1:172.19.0.2"
    - "server2:172.19.0.3"
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000

  demo-server-instance-2:
    image: menglong567:demo-server-img
    volumes:
      - /disk-2/data/docker_instances_log_store/demo-server/cluster_instance_2:/logs
    depends_on:
      - eureka-server-instance-1
      - eureka-server-instance-2
      - config-server-instance-1
      - config-server-instance-2
    container_name: demo-server-instance-2
    #network_mode:
    networks:
      extnetwork:
        ipv4_address: 172.19.0.9
    ports:
      - 8888:8888
    environment:
      - SPRING_PROFILES_ACTIVE=cluster_instance_2
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://server1:8761/eureka/,http://server2:8762/eureka/
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.19.0.10:3306/demo_service_db
      - SPRING_DATASOURCE_TOMCAT_TEST-ON-BORROW=true
      - SPRING_DATASOURCE_TOMCAT_TEST-ON-CONNECT=true
      - SPRING_DATASOURCE_TOMCAT_MAX-ACTIVE=20
      - SPRING_DATASOURCE_TOMCAT_MAX-WAIT=10000
      - SERVER_PORT=8888
    external_links:
      - mysql
    extra_hosts:
      - "server1:172.19.0.2"
      - "server2:172.19.0.3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

networks:
  serviceconfig_extnetwork:
    external: true